name: 'Update Python project: Check version / Test / git tag / GitHub Release / Deploy to PyPI'
author: 'Patrick Kidger'
description: 'Builds a Python projects, runs tests, and if successful tags and uploads to PyPI'
inputs:
    # Common inputs (without defaults)
    python-version:
        description: 'The version of Python to use. Set to `false` to not install any Python and instead use a preinstalled one.'
        required: true
    pypi-token:
        description: 'A PyPI password or authentication token for your project. Set to `false` to use some other already-configured authentication mechanism.'
        required: true
    github-user:
        description: 'Your username on GitHub.'
        required: true
    github-token:
        description: 'A GitHub authentication token for your project.'
        required: true
    test-script:
        description: 'A bash script for the tests. A uv venv will be available to install into, using `uv` directly on the PATH, e.g. commands often look like `uv sync --foo`.'
        required: true
    # Uncommon inputs (with defaults)
    pypi-user:
        description: 'Your username on PyPI.'
        default: '__token__'
    pypi-repository-url:
        description: 'The repository URL to use for PyPI, if different than the default. Passed to `twine upload --repository-url`'
        default: 'https://pypi.org/'
    checkout:
        description: 'Whether to check out the code. Set to `false` to disable this, e.g. if you have already done this.'
        default: true
    allow-first-release:
        description: 'Whether to allow doing a first release to PyPI for a package that does not already exist there. Set to `true` to allow this.'
        default: false
branding:
    icon: 'wind'
    color: 'yellow'
runs:
    using: "composite"
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          if: inputs.checkout != 'false'

        - name: Set up Python ${{ inputs.python-version }}
          uses: actions/setup-python@v2
          if: inputs.python-version != 'false'
          with:
              python-version: ${{ inputs.python-version }}

        - name: Setup
          shell: bash
          run: |
              python -m pip install --upgrade pip
              python -m pip install --upgrade build uv packaging
              python -m build

        - name: Get versions
          id: get-versions
          shell: bash
          run: |
              python -c "
              import subprocess
              import tomllib

              vparse = lambda x: tuple(map(int, x.split('.')))

              with open('pyproject.toml', 'rb') as f:
                  data = tomllib.load(f)
              name = data['project']['name']
              checkout_version = data['project']['version']

              repo_url = '${{ inputs.pypi-repository-url }}'.removesuffix('/')
              result = subprocess.run(f'python -m pip index versions {name} --index-url {repo_url}/simple --keyring-provider subprocess',
                                      shell=True, capture_output=True)
              print('Got result: ', result)
              if result.returncode == 0:
                  pypi_version = result.stdout.split(b'\n', 1)[0].split(b' ')[1][1:-1].decode('utf-8')
                  pypi_version = vparse(pypi_version)
                  new_version = str(vparse(checkout_version) > pypi_version).lower()
              else:
                  if result.stdout == b'' and '${{ inputs.allow-first-release }}' == 'true':
                      pypi_version = '<new>'
                      new_version = True
                  else:
                      raise RuntimeError('Something went wrong with getting the version from PyPI.')
              subprocess.run(f'echo name={name} >> $GITHUB_OUTPUT', shell=True)
              subprocess.run(f'echo tag=v{checkout_version} >> $GITHUB_OUTPUT', shell=True)
              subprocess.run(f'echo new-version={new_version} >> $GITHUB_OUTPUT', shell=True)
              print(f'Got checkout_version={vparse(checkout_version)!r}')
              print(f'Got pypi_version={pypi_version!r}')
              print(f'Setting name={name}')
              print(f'Setting tag=v{checkout_version}')
              print(f'Setting new-version={new_version}')
              "

        - name: Test sdist
          id: test-sdist
          if: steps.get-versions.outputs.new-version == 'true'
          shell: bash
          run: |
              cd $(mktemp -d)
              python -m uv venv
              python -m uv pip install ${{ github.workspace }}/dist/*.tar.gz --target .venv/lib/*/site-packages/
              set +e
              bash -c "
              ${{ inputs.test-script }}
              "
              if [ "$?" -eq 0 ]
              then
                  echo result=true >> $GITHUB_OUTPUT
              else
                  echo result=false >> $GITHUB_OUTPUT
              fi
              set -e
              cd ${{ github.workspace }}

        - name: Test bdist_wheel
          id: test-bdist-wheel
          if: steps.get-versions.outputs.new-version == 'true'
          shell: bash
          run: |
              cd $(mktemp -d)
              python -m uv venv
              python -m uv pip install ${{ github.workspace }}/dist/*.whl --target .venv/lib/*/site-packages/
              set +e
              bash -c "
              ${{ inputs.test-script }}
              "
              if [ "$?" -eq 0 ]
              then
                  echo result=true >> $GITHUB_OUTPUT
              else
                  echo result=false >> $GITHUB_OUTPUT
              fi
              set -e
              cd ${{ github.workspace }}

        - name: Logging
          shell: bash
          run: |
              echo new-version=${{ steps.get-versions.outputs.new-version }}
              echo sdist-result=${{ steps.test-sdist.outputs.result }}
              echo bdist-result=${{ steps.test-bdist-wheel.outputs.result }}

        - name: Push to PyPI
          if: (steps.get-versions.outputs.new-version == 'true') && (steps.test-sdist.outputs.result == 'true') && (steps.test-bdist-wheel.outputs.result == 'true')
          env:
            TWINE_USERNAME: ${{ inputs.pypi-user }}
            TWINE_PASSWORD: ${{ inputs.pypi-token }}
          shell: bash
          run: |
              if [ "${TWINE_PASSWORD}" == "false" ]; then
                unset TWINE_USERNAME
                unset TWINE_PASSWORD
              fi
              python -m pip install twine
              python -m twine upload --repository-url ${{ inputs.pypi-repository-url }} --verbose --non-interactive dist/*

        - name: Tag
          if: (steps.get-versions.outputs.new-version == 'true') && (steps.test-sdist.outputs.result == 'true') && (steps.test-bdist-wheel.outputs.result == 'true')
          shell: bash
          run: |
              git config --global user.email "noreply@example.com"
              git config --global user.name "Action: Update Python project"
              git tag "${{ steps.get-versions.outputs.tag }}" -m ""
              git push https://${{ inputs.github-user }}:${{ inputs.github-token }}@github.com/${{ github.repository }} "${{ steps.get-versions.outputs.tag }}"

        - name: GitHub release
          if: (steps.get-versions.outputs.new-version == 'true') && (steps.test-sdist.outputs.result == 'true') && (steps.test-bdist-wheel.outputs.result == 'true')
          uses: softprops/action-gh-release@v1
          with:
              name: "${{ steps.get-versions.outputs.name }} ${{ steps.get-versions.outputs.tag }}"
              body: "Autogenerated release notes as follows:"
              tag_name: "${{ steps.get-versions.outputs.tag }}"
              token: ${{ inputs.github-token }}
              generate_release_notes: true

        - name: Fail
          if: (steps.get-versions.outputs.new-version == 'true') && ((steps.test-sdist.outputs.result != 'true') || (steps.test-bdist-wheel.outputs.result != 'true'))
          shell: bash
          run: exit 1
